version: '3.8'

networks:
  kafka_network:
    driver: bridge

services:
  kafka:
    image: apache/kafka:3.9.2
    container_name: kafka-${NODE_NAME}
    environment:
      - KAFKA_NODE_ID=${KAFKA_NODE_ID}
      - KAFKA_PROCESS_ROLES=controller,broker
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:SSL,EXTERNAL:SSL,CONTROLLER:PLAINTEXT
      - KAFKA_LISTENERS=INTERNAL://0.0.0.0:9094,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      - KAFKA_ADVERTISED_LISTENERS=INTERNAL://${INTERNAL_IP}:9094,EXTERNAL://${EXTERNAL_IP}:9092
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CONTROLLER_QUORUM_VOTERS=${KAFKA_QUORUM_VOTERS}
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
      - CLUSTER_ID=${KAFKA_CLUSTER_ID}
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=${KAFKA_REPLICATION_FACTOR}
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=${KAFKA_REPLICATION_FACTOR}
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=${KAFKA_MIN_ISR}

      - KAFKA_SSL_KEYSTORE_TYPE=PEM
      - KAFKA_SSL_KEYSTORE_LOCATION=/etc/kafka/certs/kafka-keystore.pem
      - KAFKA_SSL_TRUSTSTORE_TYPE=PEM
      - KAFKA_SSL_TRUSTSTORE_LOCATION=/etc/kafka/certs/ca.crt
      - KAFKA_SSL_CLIENT_AUTH=none
      - KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM=
    ports:
      - "9094:9094"
      - "9092:9092"
      - "9093:9093"
    networks:
      - kafka_network
    volumes:
      - ./certs:/etc/kafka/certs:ro
    restart: unless-stopped
